/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TcmsCore {
        "appId": string;
    }
    interface TcmsLabel {
        "contentclass": string;
        "default": string;
        "labelid": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTcmsCoreElement extends Components.TcmsCore, HTMLStencilElement {
    }
    var HTMLTcmsCoreElement: {
        prototype: HTMLTcmsCoreElement;
        new (): HTMLTcmsCoreElement;
    };
    interface HTMLTcmsLabelElement extends Components.TcmsLabel, HTMLStencilElement {
    }
    var HTMLTcmsLabelElement: {
        prototype: HTMLTcmsLabelElement;
        new (): HTMLTcmsLabelElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "tcms-core": HTMLTcmsCoreElement;
        "tcms-label": HTMLTcmsLabelElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TcmsCore {
        "appId"?: string;
    }
    interface TcmsLabel {
        "contentclass"?: string;
        "default"?: string;
        "labelid"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "tcms-core": TcmsCore;
        "tcms-label": TcmsLabel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "tcms-core": LocalJSX.TcmsCore & JSXBase.HTMLAttributes<HTMLTcmsCoreElement>;
            "tcms-label": LocalJSX.TcmsLabel & JSXBase.HTMLAttributes<HTMLTcmsLabelElement>;
        }
    }
}
